version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
        - "5000:5000"
    volumes:
        - .:/app
    depends_on:
        - redis
    command: python app/app.py
  worker:
    build:
      context: ./task-queue
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  monitor:
    build:
      context: ./task-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
      - worker
  redis:
    image: redis
    ports:
      - "6379:6379"