version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
        - "5000:5000"
    volumes:
        - .:/app
    depends_on:
        - redis
    command: python app/app.py
  worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ./app/run_celery.sh
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"