version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    environment:
      - FLASK_DEBUG=1
    ports:
        - "5000:5000"
    volumes:
        - .:/app
    depends_on:
        - redis
    command: python app/app.py
  worker:
    image: app
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: python run-worker.py
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"